import { DocumentItem, CategoryStructure, ApprovalTask, StorageStats, AuditLogItem, UserProfile } from "../types";

export const currentUser: UserProfile = {
  id: "user-001",
  name: "Vikram Malhotra",
  email: "vikram.m@arkivex.io",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  role: "Owner",
  department: "Executive Board",
  mfaEnabled: true,
};

export const mockCategories: CategoryStructure[] = [
  { id: "cat-1", name: "Legal", icon: "Scale", docCount: 142, subcategories: ["Contracts", "NDA Agreements", "Court Papers", "MOU"] },
  { id: "cat-2", name: "Finance", icon: "DollarSign", docCount: 389, subcategories: ["Invoices", "Audits", "Bank Statements", "Budgets"] },
  { id: "cat-3", name: "Human Resources", icon: "Users", docCount: 215, subcategories: ["Employee Files", "Payroll", "NDAs", "Offer Letters"] },
  { id: "cat-4", name: "Licenses", icon: "FileCheck", docCount: 48, subcategories: ["Trade License", "FSSAI", "Factory Act", "Pollution Control"] },
  { id: "cat-5", name: "Taxes", icon: "Receipt", docCount: 184, subcategories: ["GST Returns", "Income Tax", "TDS Returns", "Form 16"] },
  { id: "cat-6", name: "Vendor", icon: "Truck", docCount: 96, subcategories: ["Vendor A Agreements", "Rate Cards", "SLA Documents"] },
  { id: "cat-7", name: "Intellectual Property", icon: "ShieldCheck", docCount: 32, subcategories: ["Trademarks", "Patents", "Copyrights"] },
  { id: "cat-8", name: "Government", icon: "Landmark", docCount: 77, subcategories: ["Compliance Filings", "Gazette Notifications", "Tenders"] },
];

export const mockDocuments: DocumentItem[] = [
  {
    id: "doc-101",
    title: "Master Vendor Agreement 2026 - Acme Corp",
    category: "Legal",
    subcategory: "Contracts",
    owner: "Siddharth Rao",
    department: "Legal Affairs",
    storageProvider: "Cloudflare R2",
    fileType: "PDF",
    fileSize: "4.8 MB",
    tags: ["Vendor", "High Priority", "GST Compliant", "Annual Renewal"],
    expiryDate: "2026-08-15",
    version: "v2.1",
    aiSummary: "Multi-year vendor agreement detailing SLAs, 30-day payment terms, and 18% GST compliance penalty clauses.",
    ocrText: "AGREEMENT BETWEEN ACME CORP AND ARKIVEX INC. GSTIN: 22AAAAA0000A1Z5. Payment terms: Net 30 days from invoice date. Termination clause requires 60 days written notice.",
    approvalStatus: "Approved",
    securityLevel: "Confidential",
    status: "Expiring Soon",
    updatedAt: "2026-07-28",
    checksum: "sha256-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    relatedFilesCount: 4,
    commentsCount: 3,
  },
  {
    id: "doc-102",
    title: "Q2 2026 Consolidated GST 3B Return Filing",
    category: "Taxes",
    subcategory: "GST Returns",
    owner: "Priya Sharma",
    department: "Finance & Accounts",
    storageProvider: "AWS S3",
    fileType: "PDF",
    fileSize: "1.2 MB",
    tags: ["GSTIN-Verified", "Q2-Filing", "Tax Return"],
    expiryDate: undefined,
    version: "v1.0",
    aiSummary: "GST 3B tax return filing confirmation for Q2 2026 showing ITC claimed ₹14,20,500 and net tax paid ₹3,10,200.",
    ocrText: "GOVERNMENT OF INDIA GST PORTAL. FORM GST 3B. Acknowledgment Receipt Number: AA2207261902839. Input Tax Credit Claimed: 1420500 INR.",
    approvalStatus: "Approved",
    securityLevel: "Internal",
    status: "Active",
    updatedAt: "2026-07-20",
    checksum: "sha256-8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
    relatedFilesCount: 2,
    commentsCount: 1,
  },
  {
    id: "doc-103",
    title: "Commercial Property Lease Agreement - HQ Premises",
    category: "Legal",
    subcategory: "Contracts",
    owner: "Vikram Malhotra",
    department: "Executive Board",
    storageProvider: "Cloudflare R2",
    fileType: "PDF",
    fileSize: "12.4 MB",
    tags: ["Lease", "Real Estate", "Stamped", "5-Year Term"],
    expiryDate: "2026-09-01",
    version: "v3.0",
    aiSummary: "Five-year commercial property lease for 14,000 sq ft office space. Monthly rent ₹4,50,000 with 5% annual escalation.",
    ocrText: "LEASE DEED REGISTERED AT SUB-REGISTRAR OFFICE. Lessor: Skylark Realty Pvt Ltd. Lessee: ArkiveX Technologies. Lease period: 60 months commencing Sept 1, 2021.",
    approvalStatus: "Approved",
    securityLevel: "Restricted",
    status: "Expiring Soon",
    updatedAt: "2026-06-12",
    checksum: "sha256-c744f4798369d7bb371752b04f762ed61d56350f55f269550b73c4d8753232bb",
    relatedFilesCount: 6,
    commentsCount: 8,
  },
  {
    id: "doc-104",
    title: "Annual Fire Safety & Pollution Clearance Certificate",
    category: "Licenses",
    subcategory: "Factory Act",
    owner: "Rajesh Kumar",
    department: "Operations",
    storageProvider: "MinIO",
    fileType: "PDF",
    fileSize: "2.1 MB",
    tags: ["Compliance", "Pollution Control", "Fire Safety", "Mandatory"],
    expiryDate: "2026-08-05",
    version: "v1.0",
    aiSummary: "Annual state pollution board NOC and fire department safety clearance for manufacturing unit 2.",
    ocrText: "STATE POLLUTION CONTROL BOARD CONSENT TO OPERATE. Valid up to 05-AUG-2026 under Water Act 1974 & Air Act 1981.",
    approvalStatus: "Pending Manager",
    securityLevel: "Internal",
    status: "Pending Approval",
    updatedAt: "2026-07-29",
    checksum: "sha256-42bb0f8a9e7019623e1f0e470a16b4792374e2d3b006efb5c391eb8bf2929d2b",
    relatedFilesCount: 1,
    commentsCount: 0,
  },
  {
    id: "doc-105",
    title: "Executive Director Employment Agreement - CTO",
    category: "Human Resources",
    subcategory: "Employee Files",
    owner: "Neha Mehta",
    department: "Human Resources",
    storageProvider: "Google Cloud Storage",
    fileType: "PDF",
    fileSize: "3.5 MB",
    tags: ["HR", "Executive", "ESOP", "NDA"],
    expiryDate: undefined,
    version: "v1.2",
    aiSummary: "Executive employment terms, ESOP vesting schedule (4 years with 1 year cliff), IP assignment, and 2-year non-compete clause.",
    ocrText: "EMPLOYMENT AGREEMENT EXECUTIVE LEVEL. Employee: Dr. Arjun Sen. Role: Chief Technology Officer. Confidentiality & IP Transfer Schedule A annexed.",
    approvalStatus: "Approved",
    securityLevel: "Confidential",
    status: "Active",
    updatedAt: "2026-05-18",
    checksum: "sha256-11f8e121544a047d81a9f029007f35a0cf07937b2fae622b7bf5718a38520844",
    relatedFilesCount: 3,
    commentsCount: 4,
  },
  {
    id: "doc-106",
    title: "Q3 IT Infrastructure Equipment Invoice #INV-9921",
    category: "Purchase",
    subcategory: "Invoices",
    owner: "Anish Verma",
    department: "IT & Hardware",
    storageProvider: "Cloudflare R2",
    fileType: "PDF",
    fileSize: "850 KB",
    tags: ["Invoice", "Dell Hardware", "Pending Payment", "GST 18%"],
    expiryDate: undefined,
    version: "v1.0",
    aiSummary: "Invoice for 15x Dell Precision Workstations and Rack Server. Total amount ₹18,45,000. Due date August 10, 2026.",
    ocrText: "DELL INDIA PRIVATE LIMITED INVOICE #INV-9921. Total Payable: 18,45,000 INR. Bank Details: HDFC Bank Current A/c 50200018274910.",
    approvalStatus: "Pending Legal",
    securityLevel: "Internal",
    status: "Pending Approval",
    updatedAt: "2026-07-30",
    checksum: "sha256-55a2989b5c392c68f117a3a89047bf1b2c45169a8b11c0349a21235b2e987112",
    relatedFilesCount: 2,
    commentsCount: 2,
  },
];

export const mockApprovalTasks: ApprovalTask[] = [
  {
    id: "app-201",
    documentTitle: "Annual Fire Safety & Pollution Clearance Certificate",
    category: "Licenses",
    requester: "Rajesh Kumar",
    requestedDate: "2026-07-29",
    stage: "Manager Review",
    status: "Pending",
    priority: "High",
  },
  {
    id: "app-202",
    documentTitle: "Q3 IT Infrastructure Equipment Invoice #INV-9921",
    category: "Purchase",
    requester: "Anish Verma",
    requestedDate: "2026-07-30",
    stage: "Legal Review",
    status: "Pending",
    priority: "High",
  },
  {
    id: "app-203",
    documentTitle: "Cloud Infrastructure SLA Amendment 2026",
    category: "Legal",
    requester: "Siddharth Rao",
    requestedDate: "2026-07-26",
    stage: "Owner Approval",
    status: "Pending",
    priority: "Medium",
  },
];

export const mockStorageStats: StorageStats[] = [
  { provider: "Cloudflare R2", usedGB: 48.2, totalGB: 100, status: "Healthy", type: "Cloud" },
  { provider: "AWS S3", usedGB: 82.5, totalGB: 250, status: "Healthy", type: "Cloud" },
  { provider: "MinIO Self-Hosted", usedGB: 14.1, totalGB: 50, status: "Healthy", type: "Self-Hosted" },
  { provider: "Google Cloud Storage", usedGB: 6.8, totalGB: 50, status: "Healthy", type: "Cloud" },
];

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: "log-901",
    timestamp: "2026-07-30 23:15:02",
    user: "Vikram Malhotra (Owner)",
    action: "DOCUMENT_VIEW",
    resource: "Master Vendor Agreement 2026 - Acme Corp",
    ipAddress: "182.73.19.42",
    securityLevel: "Confidential",
  },
  {
    id: "log-902",
    timestamp: "2026-07-30 21:40:19",
    user: "AI Assistant Engine",
    action: "METADATA_EXTRACTION",
    resource: "Q3 IT Infrastructure Equipment Invoice #INV-9921",
    ipAddress: "127.0.0.1 (Local Worker)",
    securityLevel: "Internal",
  },
  {
    id: "log-903",
    timestamp: "2026-07-30 19:22:45",
    user: "Siddharth Rao (Legal)",
    action: "APPROVAL_STAGE_ADVANCE",
    resource: "Cloud Infrastructure SLA Amendment 2026",
    ipAddress: "103.21.126.8",
    securityLevel: "Confidential",
  },
];
